jobs:
  build:
    docker:
    - image: docker:19.03.5
    steps:
    - checkout
    - setup_remote_docker:
        version: 18.09.3
    - run:
        command: DOCKER_BUILDKIT=1 docker build -t jaredallard/triton-twilight-go
          -f Dockerfile .
        name: Build Docker Image
    - run:
        command: echo "$DOCKER_PASSWORD" | docker login --username "${DOCKER_USERNAME}"
          && docker push jaredallard/triton-twilight-go
        name: Publish Docker Image
version: 2
workflows:
  build-push:
    jobs:
    - build:
        context: Docker
  version: 2
