version: 2
jobs:
  build:
    docker:
      - image: docker:19.03.1
    steps:
      # Needed for local testing
      - run: apk add --no-cache git
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: |
            set -e
            docker build -t jaredallard/triton-twilight-go -f Dockerfile .
      - run:
          name: Publish Docker Image
          command: |
            set -e
            docker login --username "${DOCKER_USERNAME}" --password "${DOCKER_PASSWORD}"
            docker push jaredallard/triton-twilight-go

workflows:
  version: 2
  build-push:
    jobs:
      - build:
          context: Docker